title: Dredge
description: "Dredge: Toil less, Code more"
url: "https://dredge.dev"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
 - jekyll-include-cache

markdown: kramdown

collections:
  docs:
    output: true
    permalink: /:collection/:path/

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dredge-dev"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-2F3FZ74TMQ"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      share: true
      related: true
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "docs"

